////////////////////////////////////////////////////////////////////////////////
//                               FastMines project
//                                                   (C) Sergey Krivulya (KSerg)
// file name: "ID_resource.h"
////////////////////////////////////////////////////////////////////////////////

#ifndef FILE_IDRESOURCE
#define FILE_IDRESOURCE

#define ID_MENU_GAME_NEW_GAME          101
#define ID_MENU_GAME_BEGINNER           102
#define ID_MENU_GAME_AMATEUR            103
#define ID_MENU_GAME_PROFESSIONAL       104
#define ID_MENU_GAME_CRAZY              105
#define ID_MENU_GAME_CUSTOM             106
#define ID_MENU_GAME_SELECTPLAYER      107
#define ID_MENU_GAME_EXIT               108
#define ID_MENU_FIGURE_TRIANGLE1   200
#define ID_MENU_FIGURE_TRIANGLE2   201
#define ID_MENU_FIGURE_TRIANGLE3   202
#define ID_MENU_FIGURE_TRIANGLE4   203
#define ID_MENU_FIGURE_SQUARE1     204
#define ID_MENU_FIGURE_SQUARE2     205
#define ID_MENU_FIGURE_PARQUET1    206
#define ID_MENU_FIGURE_PARQUET2    207
#define ID_MENU_FIGURE_TRAPEZOID1  208
#define ID_MENU_FIGURE_TRAPEZOID2  209
#define ID_MENU_FIGURE_TRAPEZOID3  210
#define ID_MENU_FIGURE_RHOMBUS     211
#define ID_MENU_FIGURE_QUADRANGLE1 212
#define ID_MENU_FIGURE_PENTAGON    213
#define ID_MENU_FIGURE_PENTAGONT5  214
#define ID_MENU_FIGURE_PENTAGONT10 215
#define ID_MENU_FIGURE_HEXAGON     216
#define ID_MENU_FIGURE_TRSQ        217
#define ID_MENU_FIGURE_TRSQ2       218
#define ID_MENU_FIGURE_SQTRHEX     219
#define ID_MENU_OPTIONS_UNKNOWN           120
#define ID_MENU_OPTIONS_TOOLBAR           121
#define ID_MENU_OPTIONS_MENU              122
#define ID_MENU_OPTIONS_CAPTION           123
#define ID_MENU_OPTIONS_TRAY              124
#define ID_MENU_OPTIONS_SKIN_LOAD        125
#define ID_MENU_OPTIONS_SKIN_SAVE        126
#define ID_MENU_OPTIONS_SKIN_CHANGE      127
#define ID_MENU_OPTIONS_ASSISTANT_ONOFF   128
#define ID_MENU_OPTIONS_ASSISTANT_OPTIONS 129
#define ID_MENU_OPTIONS_ASSISTANT_SUGGEST 130
#define ID_MENU_HELP_CAMPIONS       131
#define ID_MENU_HELP_STATISTICS     132
#define ID_MENU_HELP_REGISTRATION   133
#define ID_MENU_HELP_ABOUT          134
#define ID_MENU_OPTIONS_SKIN_LOAD0    1000 // value olways end in ID_MENU_...

#define ID_MINIMIZE               401
#define ID_BUTTON_PAUSE           501
#define ID_BUTTON_NEW_GAME        ID_MENU_GAME_NEW_GAME
#define ID_EDITCONTROL_COUNT      601
#define ID_EDITCONTROL_TIMER      602

#define ID_KEY_AREA_INCREMENT     701
#define ID_KEY_AREA_DECREMENT     702
#define ID_KEY_AREA_MAX           703
#define ID_KEY_AREA_MIN           704

#define ID_KEY_NUM0 800
#define ID_KEY_NUM1 801
#define ID_KEY_NUM2 802
#define ID_KEY_NUM3 803
#define ID_KEY_NUM4 804
#define ID_KEY_NUM5 805
#define ID_KEY_NUM6 806
#define ID_KEY_NUM7 807
#define ID_KEY_NUM8 808
#define ID_KEY_NUM9 809

#define ID_DIALOG_ABOUT_GROUPBOX    101  // button group box
#define ID_DIALOG_ABOUT_PRODUCTNAME 102  // static text "Fast Mines"
#define ID_DIALOG_ABOUT_VERSION     103  // static text "Version..."
#define ID_DIALOG_ABOUT_COPYRIGHT   104  // static text "Copyright KSerg"
#define ID_DIALOG_ABOUT_COMMENTS    105  // static text "Register/Unregister"
#define ID_DIALOG_ABOUT_RESPONSE    106  // static text "Response: e-mail"
#define ID_DIALOG_ABOUT_ICQ         107  // static text "ICQ"
#define ID_DIALOG_ABOUT_ICQADDRESS  108  // static text "72099167"
#define ID_DIALOG_ABOUT_FIDO        109  // static text "FIDO"
#define ID_DIALOG_ABOUT_FIDOADDRESS 110  // static text "2:463/444:271"
#define ID_DIALOG_ABOUT_FMSITE      111  // static text "FastMines Site:"
#define ID_DIALOG_ABOUT_UKRPOST     112  // static text "Serg_Krivulja@UkrPost.net"
#define ID_DIALOG_ABOUT_YAHOO       113  // static text "Serg_Krivulja@Yahoo.com"
#define ID_DIALOG_ABOUT_SITE        114  // static text "http://kserg77.chat.ru"
#define ID_DIALOG_ABOUT_ICON        115  // icon project
#define ID_DIALOG_ABOUT_ICON_MAIL   116  // icon mail

#define ID_DIALOG_INFO_EDIT         101

#define ID_DIALOG_STATISTICSorCHAMPIONS_TABCONTROL          101
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_BEGINNER     102
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_AMATEUR      103
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_PROFESSIONAL 104
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_CRAZY        105
#define ID_DIALOG_STATISTICSorCHAMPIONS_TABLE               106

#define ID_DIALOG_INPUTTEXT_EDIT_TEXT           101
#define ID_DIALOG_INPUTTEXT_EDIT_PASSWORD       102
#define ID_DIALOG_INPUTTEXT_EDIT_CONFIRMATION   103
#define ID_DIALOG_INPUTTEXT_STATIC_TEXT         104
#define ID_DIALOG_INPUTTEXT_STATIC_PASSWORD     105
#define ID_DIALOG_INPUTTEXT_STATIC_CONFIRMATION 106

#define ID_DIALOG_SELECTPLAYER_BUTTON_NEWPLAYER      100
#define ID_DIALOG_SELECTPLAYER_BUTTON_NEWPASSWORD    101
#define ID_DIALOG_SELECTPLAYER_BUTTON_RENAME         102
#define ID_DIALOG_SELECTPLAYER_BUTTON_REMOVE         103
#define ID_DIALOG_SELECTPLAYER_TABLE                 104
#define ID_DIALOG_SELECTPLAYER_BUTTONCHECK_AUTOSTART 105

#define ID_DIALOG_SELECTFIGURE_STATIC_NUMBER 101
#define ID_DIALOG_SELECTFIGURE_EDIT          102
#define ID_DIALOG_SELECTFIGURE_SPIN          103
#define ID_DIALOG_SELECTFIGURE_STATIC_NAME   104
#define ID_DIALOG_SELECTFIGURE_COMBOBOX      105

#define ID_DIALOG_CUSTOMSKILL_GROUPBOX      101
#define ID_DIALOG_CUSTOMSKILL_STATIC_X      102
#define ID_DIALOG_CUSTOMSKILL_STATIC_Y      103
#define ID_DIALOG_CUSTOMSKILL_STATIC_MINE   104
#define ID_DIALOG_CUSTOMSKILL_EDIT_X        105
#define ID_DIALOG_CUSTOMSKILL_EDIT_Y        106
#define ID_DIALOG_CUSTOMSKILL_EDIT_MINE     107
#define ID_DIALOG_CUSTOMSKILL_SPIN_X        108
#define ID_DIALOG_CUSTOMSKILL_SPIN_Y        109
#define ID_DIALOG_CUSTOMSKILL_SPIN_MINE     110
#define ID_DIALOG_CUSTOMSKILL_FULLSCREEN1   111
#define ID_DIALOG_CUSTOMSKILL_FULLSCREEN2   112

#define ID_DIALOG_REGFORM_STATIC_LOGIN          101
#define ID_DIALOG_REGFORM_STATIC_PASSWORD       102
#define ID_DIALOG_REGFORM_EDIT_LOGIN            103
#define ID_DIALOG_REGFORM_EDIT_PASSWORD         104
#ifdef DEBUG_REGISTRATION
#define ID_DIALOG_REGFORM_BUTTON_CREATELOGIN    105
#define ID_DIALOG_REGFORM_BUTTON_CREATEPASSWORD 106
#endif // DEBUG_REGISTRATION

#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_MINE     101
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_FLAG     102
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_PAUSE    103
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BCKGRND  104
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BTNNEW   105
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BTNPAUSE 106
#define ID_DIALOG_SELECTSKIN_BUTTON_COLOR_BCKGRND  107
#define ID_DIALOG_SELECTSKIN_BUTTON_COLOR_TEXT     108
#define ID_DIALOG_SELECTSKIN_BUTTON_TYPE_FONT      109
#define ID_DIALOG_SELECTSKIN_BUTTON_BORDER         110

#define ID_DIALOG_CHANGESKIN_BUTTON_SELECT              101
#define ID_DIALOG_CHANGESKIN_BUTTON_SELECT2             102
#define ID_DIALOG_CHANGESKIN_BUTTON_TRANSPARENTorSETALL 103
#define ID_DIALOG_CHANGESKIN_BUTTON_PLACE               104
#define ID_DIALOG_CHANGESKIN_BUTTON_CENTER              105
#define ID_DIALOG_CHANGESKIN_BUTTON_DILATE              106
#define ID_DIALOG_CHANGESKIN_BUTTON_ALONGSIDE           107
#define ID_DIALOG_CHANGESKIN_BUTTON_RESET               108
#define ID_DIALOG_CHANGESKIN_BUTTON_FRAME               109
#define ID_DIALOG_CHANGESKIN_STATIC_WIDHT               110
#define ID_DIALOG_CHANGESKIN_EDIT_WIDHT                 111
#define ID_DIALOG_CHANGESKIN_SPIN_WIDHT                 112
#define ID_DIALOG_CHANGESKIN_SPIN_TEXT                  113

#define ID_DIALOG_ASSISTANT_STATIC_UNACTIVE      101
#define ID_DIALOG_ASSISTANT_STATIC_JOB           102
#define ID_DIALOG_ASSISTANT_STATIC_MILISEC1      103
#define ID_DIALOG_ASSISTANT_STATIC_MILISEC2      104
#define ID_DIALOG_ASSISTANT_EDIT_UNACTIVE        105
#define ID_DIALOG_ASSISTANT_EDIT_JOB             106
#define ID_DIALOG_ASSISTANT_SPIN_UNACTIVE        107
#define ID_DIALOG_ASSISTANT_SPIN_JOB             108
#define ID_DIALOG_ASSISTANT_CHECKBOX_AUTOSTART   109
#define ID_DIALOG_ASSISTANT_CHECKBOX_STOPJOB     110
#define ID_DIALOG_ASSISTANT_CHECKBOX_IGNOREPAUSE 111
#define ID_DIALOG_ASSISTANT_CHECKBOX_BEEPCLICK   112
#define ID_DIALOG_ASSISTANT_BUTTON_FRAME         113

#define ID_VERSIONINFO_VERSION1  2,1,0
#define ID_VERSIONINFO_VERSION2 "2.1.0 release"
#define ID_VERSIONINFO_VERSION3 "FastMines Project - version 2.1.0."
#define ID_VERSIONINFO_VERSION4 "Version 2.1.0 (C++, WinAPI)"
#define ID_VERSIONINFO_VERSION5 "2.1.0"

#endif // FILE_IDRESOURCE
