////////////////////////////////////////////////////////////////////////////////
//                               FastMines project
//                                                   (C) Sergey Krivulya (KSerg)
// file name: "ID_resource.h"
////////////////////////////////////////////////////////////////////////////////

#ifndef __FILE__IDRESOURCE__
#define __FILE__IDRESOURCE__

#define ID_MENU_GAME_NEW_GAME          101
#define ID_MENU_GAME_BEGINNER           102
#define ID_MENU_GAME_AMATEUR            103
#define ID_MENU_GAME_PROFESSIONAL       104
#define ID_MENU_GAME_CRAZY              105
#define ID_MENU_GAME_CUSTOM             106
#define ID_MENU_GAME_CREATE            107
#define ID_MENU_GAME_SAVE              108
#define ID_MENU_GAME_LOAD              109
#define ID_MENU_GAME_SELECTPLAYER       110
#define ID_MENU_GAME_EXIT              111
#define ID_MENU_MOSAIC_TRIANGLE1   200
#define ID_MENU_MOSAIC_TRIANGLE2   201
#define ID_MENU_MOSAIC_TRIANGLE3   202
#define ID_MENU_MOSAIC_TRIANGLE4   203
#define ID_MENU_MOSAIC_SQUARE1     204
#define ID_MENU_MOSAIC_SQUARE2     205
#define ID_MENU_MOSAIC_PARQUET1    206
#define ID_MENU_MOSAIC_PARQUET2    207
#define ID_MENU_MOSAIC_TRAPEZOID1  208
#define ID_MENU_MOSAIC_TRAPEZOID2  209
#define ID_MENU_MOSAIC_TRAPEZOID3  210
#define ID_MENU_MOSAIC_RHOMBUS1    211
#define ID_MENU_MOSAIC_QUADRANGLE1 212
#define ID_MENU_MOSAIC_PENTAGONT24 213
#define ID_MENU_MOSAIC_PENTAGONT5  214
#define ID_MENU_MOSAIC_PENTAGONT10 215
#define ID_MENU_MOSAIC_HEXAGON1    216
#define ID_MENU_MOSAIC_TRSQ1       217
#define ID_MENU_MOSAIC_TRSQ2       218
#define ID_MENU_MOSAIC_SQTRHEX     219
#define ID_MENU_OPTIONS_ALWAYSMAXSIZE     120
#define ID_MENU_OPTIONS_USE_UNKNOWN       121
#define ID_MENU_OPTIONS_SHOW_TOOLBAR      122
#define ID_MENU_OPTIONS_SHOW_MENU         123
#define ID_MENU_OPTIONS_SHOW_CAPTION      124
#define ID_MENU_OPTIONS_TO_TRAY           125
#define ID_MENU_OPTIONS_SKIN_LOAD        126
#define ID_MENU_OPTIONS_SKIN_SAVE        127
#define ID_MENU_OPTIONS_SKIN_CHANGE      128
#define ID_MENU_OPTIONS_LANG_LOAD        129
#define ID_MENU_HELP_CAMPIONS       130
#define ID_MENU_HELP_STATISTICS     131
#define ID_MENU_HELP_ASSISTANT_ONOFF   132
#define ID_MENU_HELP_ASSISTANT_OPTIONS 133
#define ID_MENU_HELP_ASSISTANT_SUGGEST 134
#define ID_MENU_HELP_ABOUT          135
#define ID_MENU_OPTIONS_SKIN_LOAD0    1000 // value olways end in ID_MENU_...
#define ID_MENU_OPTIONS_LANG_LOAD0    2000 // value olways end in ID_MENU_...

#define ID_MINIMIZE               401
#define ID_BUTTON_PAUSE           501
#define ID_BUTTON_NEW_GAME        ID_MENU_GAME_NEW_GAME
#define ID_EDITCONTROL_COUNT      601
#define ID_EDITCONTROL_TIMER      602
#define ID_MOSAIC                 603

#define ID_KEY_AREA_INCREMENT     701
#define ID_KEY_AREA_DECREMENT     702
#define ID_KEY_AREA_MAX           703
#define ID_KEY_AREA_MIN           704

#define ID_KEY_NUM0 800
#define ID_KEY_NUM1 801
#define ID_KEY_NUM2 802
#define ID_KEY_NUM3 803
#define ID_KEY_NUM4 804
#define ID_KEY_NUM5 805
#define ID_KEY_NUM6 806
#define ID_KEY_NUM7 807
#define ID_KEY_NUM8 808
#define ID_KEY_NUM9 809

#define ID_DIALOG_ABOUT_GROUPBOX    101
#define ID_DIALOG_ABOUT_PRODUCTNAME 102
#define ID_DIALOG_ABOUT_VERSION     103
#define ID_DIALOG_ABOUT_COPYRIGHT   104
#define ID_DIALOG_ABOUT_COMMENTS    105
#define ID_DIALOG_ABOUT_RESPONSE    106
#define ID_DIALOG_ABOUT_ICQ         107
#define ID_DIALOG_ABOUT_ICQADDRESS  108
#define ID_DIALOG_ABOUT_FMSITE      109
#define ID_DIALOG_ABOUT_UKRPOST     110
#define ID_DIALOG_ABOUT_SITE        111
#define ID_DIALOG_ABOUT_ICON_PROJ   112
#define ID_DIALOG_ABOUT_ICON_MAIL   113

#define ID_DIALOG_INFO_EDIT         101

#define ID_DIALOG_STATISTICSorCHAMPIONS_TABCONTROL          101
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_BEGINNER     102
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_AMATEUR      103
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_PROFESSIONAL 104
#define ID_DIALOG_STATISTICSorCHAMPIONS_BUTTON_CRAZY        105
#define ID_DIALOG_STATISTICSorCHAMPIONS_TABLE               106

#define ID_DIALOG_INPUTTEXT_EDIT_TEXT           101
#define ID_DIALOG_INPUTTEXT_EDIT_PASSWORD       102
#define ID_DIALOG_INPUTTEXT_EDIT_CONFIRMATION   103
#define ID_DIALOG_INPUTTEXT_STATIC_TEXT         104
#define ID_DIALOG_INPUTTEXT_STATIC_PASSWORD     105
#define ID_DIALOG_INPUTTEXT_STATIC_CONFIRMATION 106

#define ID_DIALOG_SELECTPLAYER_BUTTON_NEWPLAYER      100
#define ID_DIALOG_SELECTPLAYER_BUTTON_NEWPASSWORD    101
#define ID_DIALOG_SELECTPLAYER_BUTTON_RENAME         102
#define ID_DIALOG_SELECTPLAYER_BUTTON_REMOVE         103
#define ID_DIALOG_SELECTPLAYER_TABLE                 104
#define ID_DIALOG_SELECTPLAYER_BUTTONCHECK_AUTOSTART 105

#define ID_DIALOG_SELECTMOSAIC_STATIC_NUMBER 101
#define ID_DIALOG_SELECTMOSAIC_EDIT          102
#define ID_DIALOG_SELECTMOSAIC_SPIN          103
#define ID_DIALOG_SELECTMOSAIC_STATIC_NAME   104
#define ID_DIALOG_SELECTMOSAIC_COMBOBOX      105

#define ID_DIALOG_CUSTOMSKILL_GROUPBOX      101
#define ID_DIALOG_CUSTOMSKILL_STATIC_X      102
#define ID_DIALOG_CUSTOMSKILL_STATIC_Y      103
#define ID_DIALOG_CUSTOMSKILL_STATIC_MINE   104
#define ID_DIALOG_CUSTOMSKILL_EDIT_X        105
#define ID_DIALOG_CUSTOMSKILL_EDIT_Y        106
#define ID_DIALOG_CUSTOMSKILL_EDIT_MINE     107
#define ID_DIALOG_CUSTOMSKILL_SPIN_X        108
#define ID_DIALOG_CUSTOMSKILL_SPIN_Y        109
#define ID_DIALOG_CUSTOMSKILL_SPIN_MINE     110
#define ID_DIALOG_CUSTOMSKILL_FULLSCREEN1   111
#define ID_DIALOG_CUSTOMSKILL_FULLSCREEN2   112

#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_MINE          101
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_FLAG          102
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_PAUSE         103
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BTNPAUSE      104
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BTNNEW        105
#define ID_DIALOG_SELECTSKIN_BUTTON_IMAGE_BCKGRND       106
#define ID_DIALOG_SELECTSKIN_BUTTON_COLOR_BCKGRND       107
#define ID_DIALOG_SELECTSKIN_BUTTON_BORDER              108
#define ID_DIALOG_SELECTSKIN_BUTTON_COLOR_TEXT          109
#define ID_DIALOG_SELECTSKIN_BUTTON_TYPE_FONT           110

#define ID_DIALOG_CHANGESKIN_BUTTON_SELECT              111
#define ID_DIALOG_CHANGESKIN_BUTTON_SELECT2             112
#define ID_DIALOG_CHANGESKIN_BUTTON_TRANSPARENTorSETALL 113
#define ID_DIALOG_CHANGESKIN_BUTTON_PLACE               114
#define ID_DIALOG_CHANGESKIN_BUTTON_CENTER              115
#define ID_DIALOG_CHANGESKIN_BUTTON_DILATE              116
#define ID_DIALOG_CHANGESKIN_BUTTON_ALONGSIDE           117
#define ID_DIALOG_CHANGESKIN_BUTTON_RESET               118
#define ID_DIALOG_CHANGESKIN_BUTTON_FRAME               119
#define ID_DIALOG_CHANGESKIN_STATIC_WIDHT               120
#define ID_DIALOG_CHANGESKIN_EDIT_WIDHT                 121
#define ID_DIALOG_CHANGESKIN_SPIN_WIDHT                 122
#define ID_DIALOG_CHANGESKIN_SPIN_TEXT                  123

#define ID_DIALOG_ASSISTANT_STATIC_UNACTIVE      101
#define ID_DIALOG_ASSISTANT_STATIC_JOB           102
#define ID_DIALOG_ASSISTANT_STATIC_SECOND        103
#define ID_DIALOG_ASSISTANT_STATIC_MILISECOND    104
#define ID_DIALOG_ASSISTANT_EDIT_UNACTIVE        105
#define ID_DIALOG_ASSISTANT_EDIT_JOB             106
#define ID_DIALOG_ASSISTANT_SPIN_UNACTIVE        107
#define ID_DIALOG_ASSISTANT_SPIN_JOB             108
#define ID_DIALOG_ASSISTANT_CHECKBOX_AUTOSTART   109
#define ID_DIALOG_ASSISTANT_CHECKBOX_STOPJOB     110
#define ID_DIALOG_ASSISTANT_CHECKBOX_IGNOREPAUSE 111
#define ID_DIALOG_ASSISTANT_CHECKBOX_BEEPCLICK   112
#define ID_DIALOG_ASSISTANT_BUTTON_FRAME         113

#define ID_VERSIONINFO_VERSION1 2,2,0
#define ID_VERSIONINFO_VERSION2 "2.2.0 beta"
#define ID_VERSIONINFO_VERSION3 "FastMines Project - version 2.2.0."
#define ID_VERSIONINFO_VERSION4 "2.2.0 (C++, WinAPI)"
#define ID_VERSIONINFO_VERSION5 "2.2.0"
#define ID_VERSIONINFO_MAJOR    "2"
#define ID_VERSIONINFO_MINOR    "2.0"

#endif // __FILE__IDRESOURCE__
